### ISSUE TITLE
Extend schema to represent work groups on several levels

### ISSUE THREAD

**Issue by marians** [netzbegruenung/green-directory#112]
The German party BÜNDNIS 90/Die GRÜNEN has working groups dealing with certain topic areas, on several regional levels.

Some of these have own websites, which is a reason for [green-spider](https://github.com/netzbegruenung/green-spider) to cover these, starting with BAG and LAG.

### Bundesarbeitsgemeinschaft (BAG)

Operating on the country level

Example: [Bundesarbeitsgemeinschaft Medien und Netzpolitik](http://bag-gruene-medienundnetz.de/)

### Landesarbeitsgemeinschaft (LAG)

Operating on the federal state level

Example: [Landesarbeitsgemeinschaft Medien NRW](http://gruene-lag-medien.de/)

### Arbeitskreis (AK): Operating on lower levels

Example: [AK Netz des KV Köln](https://www.gruenekoeln.de/arbeitskreise/kreisverband/ak-digitales.html)

### Example data/schema proposal

```yaml
---
type: WORKING_GROUP
level: DE:BUNDESVERBAND
country: DE
urls:
  - type: WEBSITE
    url: http://bag-gruene-medienundnetz.de/
---
type: WORKING_GROUP
level: DE:LANDESVERBAND
country: DE
state: Nordrhein-Westfalen
urls:
  - type: WEBSITE
    url: http://gruene-lag-medien.de/
  - type: FACEBOOK
    url: https://www.facebook.com/groups/574758192605714/
```
