### ISSUE TITLE
Please add dirk-wildt.de

### ISSUE THREAD

**Issue by dirk2014** [netzbegruenung/green-directory#183]

**Comment by marians** [comment]
@dirk2014 If you want to add a person record, please create a pull request similar to this one:

https://github.com/netzbegruenung/green-directory/pull/167

**Comment by dirk2014** [comment]
> @dirk2014 If you want to add a person record, please create a pull request similar to this one:
> 
> #167

What do you mean? Should I create a request like https://github.com/netzbegruenung/green-directory/pull/167/commits/d3a5c357b090bcce49d3dfa9bb784a1d7d7688cf
But than I need an example with a XML record for a green webiste and not for a green wiki.

**Comment by marians** [comment]
Here is an example for the YAML to be added, if the person is active on the LV level:

```yaml
---
type: PERSON
name: Dirk Wildt
family_name: Wildt
given_name: Dirk
level: DE:LANDESVERBAND
country: DE
state: Bayern
urls:
  - type: WEBSITE
    url: https://dirk-wildt.de/
emails:
  - address: byw18@dirk-wildt.de
```

Alternatively the person could be associated regionally like this:

    level: DE:BEZIRKSVERBAND
    country: DE
    state: Bayern
    region: Name des Bezirks

or

    level: DE:KREISVERBAND
    country: DE
    state: Bayern
    district: Name des Kreises
